name: Auto Merge

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'auto-merge') &&
      github.event.pull_request.draft == false &&
      github.event.pull_request.mergeable == true
    steps:
      - name: Enable auto-merge
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.enableAutoMerge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            }) 