name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Ten issue jest nieaktywny od 30 dni. Czy nadal jest aktualny?'
          stale-pr-message: 'Ten PR jest nieaktywny od 30 dni. Czy nadal jest aktualny?'
          stale-issue-label: 'no-issue-activity'
          stale-pr-label: 'no-pr-activity'
          days-before-stale: 30
          days-before-close: 7
          exempt-issue-labels: 'pinned,enhancement,bug,security'
          exempt-pr-labels: 'pinned,enhancement,bug,security'
          exempt-all-milestones: true 